# Generated by Django 5.0.2 on 2025-05-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForumHackaton', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalement',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
